import express from "express";
import { randomUUID } from "node:crypto";
import { inputSchema, serviceHandler } from "./service.js";
import { Lifecycle, MemoryJobStore, PostgresJobStore, createCrooAdapter } from "./runtime.js";
const store=process.env.DATABASE_URL?new PostgresJobStore(process.env.DATABASE_URL):new MemoryJobStore();
if(store instanceof PostgresJobStore)await store.migrate();
const lifecycle=new Lifecycle(store,async(input,context)=>serviceHandler(inputSchema.parse(input),context),{agentId:process.env.CROO_AGENT_ID??"unregistered",serviceId:process.env.CROO_SERVICE_ID??"unregistered",version:"1.0.0"});
const app=express();app.use(express.json({limit:"64kb"}));
app.get("/",(_,res)=>res.type("html").send("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width'><title>"+(process.env.SERVICE_NAME??"CROO Agent")+"</title><style>body{font-family:system-ui;background:#07111f;color:#e7f0ff;max-width:900px;margin:10vh auto;padding:24px}code{color:#62e6a7}.card{border:1px solid #24425e;border-radius:16px;padding:24px;background:#0c1a2b}</style></head><body><div class=card><p>CROO Agent Commerce Suite</p><h1>"+(process.env.SERVICE_NAME??"Independent agent")+"</h1><p>Evidence-backed paid agent with durable CAP lifecycle processing.</p><p><code>GET /health</code> · <code>POST /v1/analyze</code> · <code>GET /jobs/:id</code></p></div></body></html>"));
app.get("/health",(_,res)=>res.json({ok:true,service:process.env.SERVICE_NAME,mode:process.env.CROO_SDK_KEY?"croo":"local"}));
app.get("/jobs/:id",async(req,res)=>{const j=await store.get(req.params.id);res.status(j?200:404).json(j??{error:"not found"});});
app.post("/v1/analyze",async(req,res)=>{try{res.json(await lifecycle.process("local-"+randomUUID(),req.body));}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)});}});
app.listen(Number(process.env.PORT??3000),()=>console.log(JSON.stringify({level:"info",event:"listening",port:Number(process.env.PORT??3000)})));
if(process.env.CROO_SDK_KEY)createCrooAdapter(lifecycle).catch(e=>{console.error(e);process.exitCode=1;});
